// <auto-generated />
using Manruka.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Manruka.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210142117_AddRoomEntity")]
    partial class AddRoomEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Manruka.API.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 60,
                            Description = "Lantai 3",
                            IsAvailable = true,
                            Name = "C-301"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 60,
                            Description = "Lantai 3",
                            IsAvailable = true,
                            Name = "C-302"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Description = "Lantai 1",
                            IsAvailable = true,
                            Name = "C-105"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 30,
                            Description = "Lantai 1",
                            IsAvailable = true,
                            Name = "C-103"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 60,
                            Description = "Lantai 2",
                            IsAvailable = true,
                            Name = "B-204"
                        });
                });

            modelBuilder.Entity("Manruka.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Major")
                        .HasColumnType("text");

                    b.Property<string>("NRP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearEntry")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NRP")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
